// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edqjskmaorvfxluojsth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkcWpza21hb3J2ZnhsdW9qc3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTYzMTksImV4cCI6MjA2NDU3MjMxOX0.LDDtsJJCtpZ_LAWJjKeDeviodH6pErpVISb0ZzCE_gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});